/// Flutter icons Bash_Iconography
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bash_Iconography
///      fonts:
///       - asset: fonts/Bash_Iconography.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bash_Iconography {
  Bash_Iconography._();

  static const _kFontFam = 'Bash_Iconography';
  static const String? _kFontPkg = null;

  static const IconData shopping_cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_card = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric_moped = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData receipt = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData straighten = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sell = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData storefront = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_mall = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_shipping = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData local_activity = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData package_2 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
