/// Flutter icons Bash_Iconography
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bash_Iconography
///      fonts:
///       - asset: fonts/Bash_Iconography.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bash_Iconography {
  Bash_Iconography._();

  static const _kFontFam = 'Bash_Iconography';
  static const String? _kFontPkg = null;

  static const IconData shopping_cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
